# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .. import Provider as LoremProvider


class Provider(LoremProvider):
    word_list = (
        'adanji',
        'baH',
        'baktag',
        "bat'leth",
        'Bekk',
        "CHEGH-chew jaj-VAM jaj-KAK",
        'Dah!',
        "d'akturak",
        "d'blok",
        "Dhak'tah",
        "d'k tahg",
        "Fek'lhr",
        'Forshak',
        'ghoptu',
        'Ghos!',
        "gik'tal",
        "Gre'thor",
        "he'HlmaH",
        "Ha'DlbaH!",
        "Hechu'ghos",
        "Hljol",
        "hu'q",
        "in'cha",
        "jagh",
        "hak'tahla",
        "Jatlh",
        "jat'yln",
        "Jelik",
        "jinaq",
        "J'khat bah",
        "k'adio",
        "kajunpak't",
        "ka'vek",
        "ke'chaw",
        "kellicam",
        "kesh",
        "kji-GOSH",
        "Kolat chack tabak",
        "koruts",
        "k'pekt",
        "Kortar",
        "Kos'Karii",
        "ko'tal",
        "kut'luch",
        "Kyamo",
        "Len'mat",
        "Lohd Zoss-lee chaw-Ku sohk jaTAL",
        "Mak'dar",
        "Maj ram",
        "mahk-cha!",
        "mat-LEH",
        "Mauk-to'Vor",
        "mek'leth",
        "mevak",
        "mok",
        "Mok'tah",
        'movek',
        "nlb'poH",
        "Nuq'nuh",
        "Quee nagah",
        "par'Mach",
        "par'Machkai",
        "petaQ",
        "Po'tajg!",
        "Pu'Dah dak cha",
        "Qapla",
        "qhonDog",
        "qi'von",
        "Quee nagah",
        "Qui'Tu",
        "qu'valth",
        "shuVak",
        "Sli Vak",
        "soh-chim",
        "so'wl'chu'",
        "Sowee TAH",
        "Sto-vo-kor",
        "SuH",
        "Suvwl'",
        "t'gla",
        "taHqeq",
        "tohzah",
        "toruk-doh",
        "vang ghaH!",
        "yan",
        "Yintagh",

    )